### ISSUE TITLE
Not working on Android Emulator

### ISSUE THREAD

**Issue by aniruddhasm** [mdpauley/com.mp5systems.rippleeffect#2]
It's not working on android emulator I also getting the below warning message
View: View too large to fit into drawing cache, needs 8294400 bytes, only 1536000 available

**Comment by mdpauley** [comment]
Tried using a Genymotion Nexus 4 4.4.4 image and error is reproducible. The error is due to the initial [scale](https://github.com/mdpauley/com.mp5systems.rippleeffect/blob/master/controllers/widget.js#L15) and/or the [scale](https://github.com/mdpauley/com.mp5systems.rippleeffect/blob/master/controllers/widget.js#L33) in the animation. Trying a few ideas now to fix.

**Comment by aniruddhasm** [comment]
Thanks for quick replay. Hope you get the solution.
I really appreciate your work.

**Comment by mdpauley** [comment]
Fixed in latest commit. Moved the initial transform and center to the first animation.

**Comment by aniruddhasm** [comment]
Yes, It is working perfectly. Thanks
